# Generated by Django 4.2.6 on 2024-07-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_document_documentofirmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='redirect_url',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
    ]
