# Generated by Django 4.2.6 on 2024-07-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_alter_document_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='url_firma',
            field=models.TextField(blank=True, default=''),
        ),
    ]
