# Generated by Django 4.2.6 on 2024-07-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_document_url_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dni',
            field=models.CharField(default='00000000', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='document',
            name='nombre_y_apellido',
            field=models.CharField(default='Nombre Apellido', max_length=255),
        ),
    ]
