# Generated by Django 4.2.6 on 2024-07-08 21:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0008_document_dni_document_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='document',
            name='ubicacion_geografica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
